apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: monitoring
  releaseName: loki-stack
  dependsOn:
    - name: kube-prometheus-stack
  chart:
    spec:
      version: "2.x"
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 60m

