apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 10m
  timeout: 5m
  dependsOn:
    - name: services
  sourceRef:
    kind: GitRepository
    name: poshcode
  path: ./apps
  prune: true
  wait: true
  decryption:
    provider: sops
  commonMetadata:
    annotations:
      poshcode.org/tenant: sre-team