apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  interval: 10h
  retryInterval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: poshcode
  path: ./crds
  prune: true
  wait: true
  commonMetadata:
    annotations:
      poshcode.org/tenant: sre-team
