apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: issuers
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 10m
  timeout: 5m
  dependsOn:
    - name: services
  sourceRef:
    kind: GitRepository
    name: bootstrap
  path: ./system/issuers
  prune: true
  wait: true
  commonMetadata:
    annotations:
      poshcode.org/tenant: sre-team
