apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: system
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 10m
  timeout: 5m
  dependsOn:
    - name: crds
  sourceRef:
    kind: GitRepository
    name: poshcode
  path: ./system
  decryption:
    provider: sops
  prune: true
  wait: true
  commonMetadata:
    annotations:
      poshcode.org/tenant: sre-team
