apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- secret-dex.yaml # this one worked: secret-azuread.yaml
- middleware/forward-auth.yaml
- letsencrypt-production.yaml
- letsencrypt-staging.yaml

#
# Configs
#
configMapGenerator:
- name: configs
  namespace: traefik
  files:
    - middleware/forward-auth.ini
