apiVersion: v1
kind: Secret
metadata:
    name: azuread
    namespace: traefik
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:sCfZJd6I7q+SYbbTLoMuwSBQ29yrMGI7NcqIkIqvwkGA/hgp,iv:xOPUQQZ+ttuSBZOZiXjEwdw/3AyDGrkP7Acbblml3XE=,tag:GekowfCWQ3nkTE3t3tMmXA==,type:str]
    client_secret: ENC[AES256_GCM,data:o2/+CVks9b7lfP+7BthOZthXjw4ybVrH40Ejm0xrPRRYbCQiYz8bbg==,iv:h/2mPPNzZqyHu/WrdQA7rmmM0of7IQ+uNOpSgdJ1Q7w=,tag:UCmFObw3ROGHTefY7KQ60Q==,type:str]
    issuer_url: ENC[AES256_GCM,data:IWlXDDDhX0sjJUp0Z7Xpqzk0s+XmBNezUhBMxI7oTxK5YEUqUeIMtQp++o5kBIug7KtVQHrfa5w7ZFE4XBSlndjCGLuTl3hTZuAr,iv:uJyhAQucntq7DhNCAZu+FMFXwIRezYgCxjItu8cwtqI=,tag:q3tMAexsLT9uPjeevzWc/w==,type:str]
    secret: ENC[AES256_GCM,data:KojcrySOMeqY2ZvE6HcOaqb/sv+jPQjleG/mUfHs8/OvCoFD,iv:YRgKpkEtz+6GyjCqSxRmxB7SwOHLLNC8EMqUoVG2pC0=,tag:UFjCiT1d2ZlzBDd1OW6s9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://kv-joel.vault.azure.net
          name: sops-key
          version: 5ef3f03a360140bbb419a997adb4ea3d
          created_at: "2023-10-14T23:28:54Z"
          enc: SfdjlemWcR6lTzmZ_Dc2JfXIDhb1R-9sjOfdu2g--MDdJtu-i3pUUBqIBsTmSsrer_fKeQ2dvOdGEUHVZRU08mB8SRRgt3AHFRxqJY1pXERZ1GJw3xHQOC0MYpN4z2BvQKPo3sDBhmeJjqWN3h6Ko0EJ6YEAhGkZQQJV9KRSL-N-LxZvxeZbL7_CYbFGo0bAmk3m6ToMjSjzlExgBsS5IOE-xXZZaZMa79GTM7F11CaprJjl3mCDdyMqHhDfk2zizHT74RwMqt9soqoxl-l0ciNh7zsyIZ9flKk-YlnRvK39Isb63itYA8xiZKqNKJvboLPdz20IOksHlLMFcuzMzkllJL01DMQfwLFS71esZN8-8UO5bQIipze_RtcsVDEAAZZe9r0MSfH4XU6g0hcQliHoH0Vugp8S95FhD5b0ld9FIfPRVZbwPEoFjHC7MoXDPWzQJ3QoTLGEBfGfnsODzc1myZbn-XCorb8uiGmo-ELvixkbexokYgGjoENLW4tVX0r_np8XpJRE9ypODEaZ5zhJZgk_f7MUVXgCYrpQBaavA8bfbUTju1ekHOFb-u__Hsb_JVMtJoSzZ8VXjABjDwxCCsYcMqnmdOe5FK006jxbzJ_fNWqrU_rhb9Isi5JDP-WIywUFhFtz6WKpyBH879qVekw1eYgmi5qzx8eU6WE
        - vault_url: https://kv-poshcode.vault.azure.net
          name: sops-key
          version: f49a0e054ffe451a85df33e5cdf7946a
          created_at: "2023-10-14T23:28:54Z"
          enc: lmVSGhsVPd5dYCrpvqCRSrOVgzK4bzZ6jbkWWYF6D23xlw58b9FNryWEBQGRy6azD9O6sA0kROlZZHfJY8xI4WbQ-01zhW9MxCaX-HoQ1NebFqX7dm_3udYabsLkiM4I0uCbgAAOthGT1V6nR2Sp6j-q42NPQanWtEkAIJu1-1Rr58ppVKFDOO6BOIk0ez3QpD0FLh9L_HGsvJE1WdmUE0sW2RgRJOYfAn4RU7VI6N8JGZKY-sIha8Wqjat0pG-410DW-3eVaCoKrHd55BVfIRyBbKyilIYfIt4yfnGsF38m27qEjdP4FubjbA0_OlCJDYaGvCV3qEaiMbwWUuixlw
    hc_vault: []
    age:
        - recipient: age12nc5tc37e70nxpjn7rulvn650l6wztftq75audd4nftpue4jp3uqdac6el
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRm1VdVNUdy9hTm9VZGgz
            NzJmSkQ1Ums5QzNJY0xiSDVtWG1hSlMxVURFClhpbm4rZTIzSDVBZlk4MkFxMHhJ
            RWtmMWJiY01OWHBiNUhXNk1MemZ2K28KLS0tIGVVNVhyVWV1OVF0RTlCTTJIRUhq
            U0IzNWRwdGh6Nm1HSVdaZFlQcUJaejQKCMCaikKSP8/scY8rYVeWbesxfwQ+FyJm
            DKg7c/bddWbcd8o68HYytIx7smT+GURzD1L6ed3ORxbp5pkUEUqLdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-14T23:28:58Z"
    mac: ENC[AES256_GCM,data:GjHyZT5IbWqgH4S+9nnWBGPFnEPDbZNRpkeA6jpMJDHUDiBULWGhrXbFaRPWC9yDPZXP/DMSCbyVl4JWGoy80t8K2yPRzq3NMn4qACOQ74kex4fMxpz7dshNe6s/FkZav4bZaJ8v15rlWY73A4eBcMn/oY5rn9Qwt7j8DWtU3Uk=,iv:tqmb/1DfAJff9KbuYbY/f/JhP6qpyaJDbp+9OCSzAOs=,tag:wLL2mKD1uuYmrYJvsZvMZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
