namespace: podinfo

resources:
- namespace.yaml
- repository.yaml
- release.yaml
- http-route.yaml

configMapGenerator:
- name: podinfo-values
  files:
  - values.yaml=podinfo-6.6.1-values.yaml

configurations:
- valuesfrom.yaml
