apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 30m
  timeout: 5m
  releaseName: podinfo
  targetNamespace: podinfo
  chart:
    spec:
      chart: podinfo
      version: ">6.0.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
      interval: 12h
  install:
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 3
  rollback:
    timeout: 5m
  valuesFrom:
  - kind: ConfigMap
    name: podinfo-values
