resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml

configMapGenerator:
  - name: traefik-values
    namespace: flux-system
    files:
      - values.yaml=traefik-values.yaml

configurations:
  - valuesfrom.yaml