apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - secret.yaml
  - routes.yaml

configMapGenerator:
  - name: dex-values
    namespace: flux-system
    files:
      - values.yaml=dex-0.16.0-values.yaml

configurations:
  - valuesfrom.yaml