apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dex
  namespace: dex
spec:
  hostnames:
  - dex.poshcode.com
  parentRefs:
  - namespace: networking
    name: damascus
    sectionName: https-dex
  rules:
  - backendRefs:
    - name: dex
      port: 5556
    matches:
    - path:
        type: PathPrefix
        value: /
