apiVersion: v1
kind: Secret
metadata:
    name: github-client
    namespace: dex
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:R103ZIirBtSX39xUaup60+Ixn+Y=,iv:AB74hy/p7TZHNlq8tYEfLvVQsSFvaJVa7eKtoUww5EI=,tag:ISwJM2IU2432uKiRXUuReQ==,type:str]
    client-secret: ENC[AES256_GCM,data:tmHVyL3yzzHuMl5tnlrPOJocHmjbgbZFRh58nk9p4QV/y8NwLidlaw==,iv:brgBjT9cgAW5KS3lvVe+hSvoZOsDjtCedsHfJE5u4pY=,tag:POWBKGsR+FU2uNvB/EU+fA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://kv-joel.vault.azure.net
          name: sops-key
          version: 5ef3f03a360140bbb419a997adb4ea3d
          created_at: "2023-12-15T05:55:51Z"
          enc: DYemf3DzUO3mzvCW4KomdCNR_XcBQfzT7HYwLXoo4OKbq7b7gvh_qNo1pv7WeHmXitHMe6KrDXnWrhQLxghv9B7c0dRJkyNu-AT2pLCfyDflmlrsCys3IXru86zoDMEZ3y9JwHSud0VdHO-mbApT6ahaWYwy7YJ6cw_2tRd2inIH3arTVq8OiYxwpiJZB6N-fODQt6yXegffAbjanF5nlUN020m8oiHQiNwOkvcRfoSPw6z1sFw1f-XCnejiAmHLw-cLl4uoOVXSw8OwT7uKFJNtmCe72TKn9R96IUyMPcUA541vYDBVA1Txa3ye44yP43WzLr16Orif61g-Ccr1X1mTsobaI-Kzf-fIywBE2QsuRFGCrfySAGtk43CovfFolwYNI6_kBj1Jhciy2TFtgHUDhF8AyXuCHz9-kR6jz2g6ljDkBvSj2z4q2XX1U2bEdrwbLny_XfVJoxBh42md00bQm-UN5g-UZ44rvQJc-XFf2itufB2Henc7hqpQIheh8PhhzWN8Z_iXBI_pei4rwy8f1rGmL_kIAfwkNJkgmJgV7pV2cv1STXpajd84Ab0Gf3FP7RX_XybNjCYSO46cED9oOtF0OMXOwmf_Lj3eRNA8Bv2rhG9SArpUP2hEidNqtWcn4wJNxdxONuoBoHN0BinfU-pDChoTu1Urcd4S1Rw
        - vault_url: https://kv-poshcode.vault.azure.net
          name: sops-key
          version: f49a0e054ffe451a85df33e5cdf7946a
          created_at: "2023-12-15T05:55:51Z"
          enc: NAi2UXsPWQxn5dyLkK78Hs2zRb9ICpYG-ZwrDbBtIAbc82DjMiFuv7FMkWijf5pdl-jySqHzfw8nlZ3Pxxu76_bbV0QEDJK6nxKQT8IIGB4QeqsK5D8Jcq0w2QU9YiWQgbQmK7nKHAf_sAcS9cNihJ-X0Dm1QnUq4KEieUaQLA2u7ORokN4MXFFdyM4Wa5hlHQI1L-pRF6AnzZ3TKsUp5170aXzshVHUOuRmJSao1NgCWMSI6jyTh15yn6ESONcMQuHA5d_BtwWy1gAUDwP2jt8_DQ9podapDhHUQGtAB4gdt6jk-tn_hXQnGHc_61ovEatQmbl1xm2ABc-VxFKVVA
    hc_vault: []
    age:
        - recipient: age12nc5tc37e70nxpjn7rulvn650l6wztftq75audd4nftpue4jp3uqdac6el
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3S2dkVWFEYmlURm45WXc0
            aUtqOUlJSnh1UHU5dFhBcWViYWFBdjJRdDNjCmpjMm9ETVY2NE53UXB0dHJkZHUy
            Rm1FT1dIRUhKNlQwemZibVFiRmxyYU0KLS0tIGpocHVKekozNUpCSEZFRTVxeVZa
            amgzSG9sMzhYNUZOSXNXZVdWVVUzTUUK0kYXyDmvGoJrKyobjOgsYRqSoo4aA8II
            xDkVFZsB+l9b38icBthVZ0HRueWSOas6ocAT3Ja2gaOXizfqNML0SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-15T05:55:55Z"
    mac: ENC[AES256_GCM,data:0Hyu0VNaLlF2QADjVY8ECen7Bl7h6psSSJ2SxiBZWFb4uEqACueTROpufjPA2UOKX2a8cb/swdek5BhCsgLG2HXwQ2ELX+4BNh5oY/Tex+fI94/hGh9t0Qu5gDKhM+SnWLUHIm8LmP2OuRgxivce3sBJoea2Q5YuOomG6grVtvw=,iv:iv1TqnpSPcGXM6ulIW3M8usIfpihkQ7hsrxKyu7eAmM=,tag:IN7gZ8txzipaXQUW9aCFdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forward-auth
    namespace: dex
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:RCBV+Ouh9gmMdmOL54JU0/ZqX5NLTXmU8RmANrF6fZM=,iv:l3ckVZWu15fPySoUB0YaT6/1WrEi2qmGzWBEuLHtkq0=,tag:/HbtpqzJNP8jP8jmHatdIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://kv-joel.vault.azure.net
          name: sops-key
          version: 5ef3f03a360140bbb419a997adb4ea3d
          created_at: "2023-12-15T05:55:51Z"
          enc: DYemf3DzUO3mzvCW4KomdCNR_XcBQfzT7HYwLXoo4OKbq7b7gvh_qNo1pv7WeHmXitHMe6KrDXnWrhQLxghv9B7c0dRJkyNu-AT2pLCfyDflmlrsCys3IXru86zoDMEZ3y9JwHSud0VdHO-mbApT6ahaWYwy7YJ6cw_2tRd2inIH3arTVq8OiYxwpiJZB6N-fODQt6yXegffAbjanF5nlUN020m8oiHQiNwOkvcRfoSPw6z1sFw1f-XCnejiAmHLw-cLl4uoOVXSw8OwT7uKFJNtmCe72TKn9R96IUyMPcUA541vYDBVA1Txa3ye44yP43WzLr16Orif61g-Ccr1X1mTsobaI-Kzf-fIywBE2QsuRFGCrfySAGtk43CovfFolwYNI6_kBj1Jhciy2TFtgHUDhF8AyXuCHz9-kR6jz2g6ljDkBvSj2z4q2XX1U2bEdrwbLny_XfVJoxBh42md00bQm-UN5g-UZ44rvQJc-XFf2itufB2Henc7hqpQIheh8PhhzWN8Z_iXBI_pei4rwy8f1rGmL_kIAfwkNJkgmJgV7pV2cv1STXpajd84Ab0Gf3FP7RX_XybNjCYSO46cED9oOtF0OMXOwmf_Lj3eRNA8Bv2rhG9SArpUP2hEidNqtWcn4wJNxdxONuoBoHN0BinfU-pDChoTu1Urcd4S1Rw
        - vault_url: https://kv-poshcode.vault.azure.net
          name: sops-key
          version: f49a0e054ffe451a85df33e5cdf7946a
          created_at: "2023-12-15T05:55:51Z"
          enc: NAi2UXsPWQxn5dyLkK78Hs2zRb9ICpYG-ZwrDbBtIAbc82DjMiFuv7FMkWijf5pdl-jySqHzfw8nlZ3Pxxu76_bbV0QEDJK6nxKQT8IIGB4QeqsK5D8Jcq0w2QU9YiWQgbQmK7nKHAf_sAcS9cNihJ-X0Dm1QnUq4KEieUaQLA2u7ORokN4MXFFdyM4Wa5hlHQI1L-pRF6AnzZ3TKsUp5170aXzshVHUOuRmJSao1NgCWMSI6jyTh15yn6ESONcMQuHA5d_BtwWy1gAUDwP2jt8_DQ9podapDhHUQGtAB4gdt6jk-tn_hXQnGHc_61ovEatQmbl1xm2ABc-VxFKVVA
    hc_vault: []
    age:
        - recipient: age12nc5tc37e70nxpjn7rulvn650l6wztftq75audd4nftpue4jp3uqdac6el
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3S2dkVWFEYmlURm45WXc0
            aUtqOUlJSnh1UHU5dFhBcWViYWFBdjJRdDNjCmpjMm9ETVY2NE53UXB0dHJkZHUy
            Rm1FT1dIRUhKNlQwemZibVFiRmxyYU0KLS0tIGpocHVKekozNUpCSEZFRTVxeVZa
            amgzSG9sMzhYNUZOSXNXZVdWVVUzTUUK0kYXyDmvGoJrKyobjOgsYRqSoo4aA8II
            xDkVFZsB+l9b38icBthVZ0HRueWSOas6ocAT3Ja2gaOXizfqNML0SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-15T05:55:55Z"
    mac: ENC[AES256_GCM,data:0Hyu0VNaLlF2QADjVY8ECen7Bl7h6psSSJ2SxiBZWFb4uEqACueTROpufjPA2UOKX2a8cb/swdek5BhCsgLG2HXwQ2ELX+4BNh5oY/Tex+fI94/hGh9t0Qu5gDKhM+SnWLUHIm8LmP2OuRgxivce3sBJoea2Q5YuOomG6grVtvw=,iv:iv1TqnpSPcGXM6ulIW3M8usIfpihkQ7hsrxKyu7eAmM=,tag:IN7gZ8txzipaXQUW9aCFdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
