apiVersion: v1
kind: Secret
metadata:
    name: github-client
    namespace: dex
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:RhDrkx1hZFL8v+kC23tBT57foAU=,iv:yZB4ZnG3hFoxgMHr+lIC+f2s0dk3odXs70bXeSOzJH8=,tag:hVUloeRlGC/3aSvi+nG6Tg==,type:str]
    client-secret: ENC[AES256_GCM,data:v5VoZFKREqFqzq6EzozJJjTUhNBZPf7mMEssrhHJbwtG8kK7akXVvg==,iv:4zQOdTzadms6pJhI1Vt1dnaoLrAO2KmaEbGKwe/WrP4=,tag:13A+ybh557ORfKBgOJkSVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://kv-joel.vault.azure.net
          name: sops-key
          version: 5ef3f03a360140bbb419a997adb4ea3d
          created_at: "2024-04-01T22:28:19Z"
          enc: Q_mFE8WztqMYIrkhPRfxO5LLrjL95tn1AD_0b7CFW0algeogEZgubTrc8mf6VxiCQE2_TIDz7tjqJw9JYVkjFtIbzf8Y6P95zV2N39yLDRPBYbnwyPUOZdYrCk31MKJbqiP6pxOStOiMpRkpLhJmYdNFg2HG6tDbijvMl5nfH_AtibDBoLRyEKk0jANlpySHwcC0WB-jdcMB8u88wDepr6gXjtHDwkPraXdtCEIwbmVKSdAM_7-2bvOFd95F4viIDhP7_56vspGWiPhWpBRNyLbv9KZ9QkTWioZOeO9hmQjcs3rq0b30uozrdExThmOaBbKCkXu_bmb8OWC-92ve576riRYH4bj4OVedhjL6ysRlQCncSbkYIeyoo-F7jKkdql2f2pRNvkZGU1PhA_MuwYJtItbm1XHDcLyb3gseoEZTLM3EPylb4KTQP7Kbig_WmeiliIibZKKkCr4Wl1KVlFforgXfvQsG81BevZZj6y2k581xRKDxVrbkBBX9b408_1Rni_m1k04K-Z1PhtzsFq2sKIkvlED__bEEQphtWn6_BzIh4GDZKwIRbyW8E9D5RlzSpoOm8-gkScPTo4tcH-AI-BCDnbqF8s7kkkTl_OvBN2vLHjhoG82RTgug8u9DiwBshOEcKgTEb5YnJhiTdj0ke1nEetbuA7SrlHXAns8
        - vault_url: https://kv-poshcode.vault.azure.net
          name: sops-key
          version: f49a0e054ffe451a85df33e5cdf7946a
          created_at: "2024-04-01T22:28:19Z"
          enc: T3etW8vHL1Kdlgh6xM4tXU5iZIR5oM2-f_m5rYMtCVBBf3qdBp1guPNWmLs9M50zbKbzel1ev6dxQkwMoBxTimjRgcMvK5ecHk8RNnhsq5BTBXFENM4_IkChuvnL9sWE3_p-y-aEjPUaY8_hm9Kpo7oyQ4SBJ1360KlaxXCkc3MBIIO1oIafoKW60bwWXXq-mb_oESkLV9LDqh_bfPFsZSPe8io4BgFsDXlL5T-PB4NOG38KjpSrZO4pXzxLDXi5c_FFNGLHCbG1KkkB55GCHF4oTBzg1xi7oYgjFY46NbcnbNQaZK2kypqgSrpbpjJeaIF0_EK3wWs4Ix0rlzQR3Q
    hc_vault: []
    age:
        - recipient: age12nc5tc37e70nxpjn7rulvn650l6wztftq75audd4nftpue4jp3uqdac6el
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOXovRnl5YUlqZ1pOOTZT
            MzE4dm5naHRaSzVKUEpUejNQMzhuT3pPbVZJCnhVYkhaM3hDdS9RU0VQTU9MMW54
            N05pdVdqYmZHaTdmRkZySkFBbnQ2aVkKLS0tIFk5eVNzN0tXTW1EWXN4Ynl2eUJT
            YWxUQzVaREFDQktQY09mbWVLRE1LNjAK2N1lXkb+1tS+jiM2fQ8XDxiOhyRfmRnz
            LEIqh4sIRcFDb3W7FOT43u5xbsLnLPaGw6PSsAgUVHk7JpKx/Oah7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-01T22:28:23Z"
    mac: ENC[AES256_GCM,data:c1zGd/AEazVQ24C3a6rFR24skCuaZjI/eUtX7kR7HCfOKs24egGK73lKwb9YXVJ2qUOtypkygM7URfwewV6I0Fk2t5s9YIAhaBGND3WeilulwNAgX1tcBUWyCF+EfrF2lbBO+dmo92uFrfTLoeBjCvdCZbehj4uoyNAlkjkYQew=,iv:Cu1tuUiSARvmVrlDObuyatSEE0Uw3jCUQrqEV81UdWU=,tag:tcYTRKaPsJuWePxRRLWvgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
---
apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-kube-prometheus-stack
    namespace: dex
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:flPYmLgFH/Q5fMuOnEFTvByjSpb7k76oXeREeEzkYW6UFUA5LMNAxpFue7s=,iv:kUtWhD1ZDzTPbYJF4G7gBM/eTdwKoK0W11+kNsSbF+I=,tag:rsDLYFlzzqFjG30fLTpJOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://kv-joel.vault.azure.net
          name: sops-key
          version: 5ef3f03a360140bbb419a997adb4ea3d
          created_at: "2024-04-01T22:28:19Z"
          enc: Q_mFE8WztqMYIrkhPRfxO5LLrjL95tn1AD_0b7CFW0algeogEZgubTrc8mf6VxiCQE2_TIDz7tjqJw9JYVkjFtIbzf8Y6P95zV2N39yLDRPBYbnwyPUOZdYrCk31MKJbqiP6pxOStOiMpRkpLhJmYdNFg2HG6tDbijvMl5nfH_AtibDBoLRyEKk0jANlpySHwcC0WB-jdcMB8u88wDepr6gXjtHDwkPraXdtCEIwbmVKSdAM_7-2bvOFd95F4viIDhP7_56vspGWiPhWpBRNyLbv9KZ9QkTWioZOeO9hmQjcs3rq0b30uozrdExThmOaBbKCkXu_bmb8OWC-92ve576riRYH4bj4OVedhjL6ysRlQCncSbkYIeyoo-F7jKkdql2f2pRNvkZGU1PhA_MuwYJtItbm1XHDcLyb3gseoEZTLM3EPylb4KTQP7Kbig_WmeiliIibZKKkCr4Wl1KVlFforgXfvQsG81BevZZj6y2k581xRKDxVrbkBBX9b408_1Rni_m1k04K-Z1PhtzsFq2sKIkvlED__bEEQphtWn6_BzIh4GDZKwIRbyW8E9D5RlzSpoOm8-gkScPTo4tcH-AI-BCDnbqF8s7kkkTl_OvBN2vLHjhoG82RTgug8u9DiwBshOEcKgTEb5YnJhiTdj0ke1nEetbuA7SrlHXAns8
        - vault_url: https://kv-poshcode.vault.azure.net
          name: sops-key
          version: f49a0e054ffe451a85df33e5cdf7946a
          created_at: "2024-04-01T22:28:19Z"
          enc: T3etW8vHL1Kdlgh6xM4tXU5iZIR5oM2-f_m5rYMtCVBBf3qdBp1guPNWmLs9M50zbKbzel1ev6dxQkwMoBxTimjRgcMvK5ecHk8RNnhsq5BTBXFENM4_IkChuvnL9sWE3_p-y-aEjPUaY8_hm9Kpo7oyQ4SBJ1360KlaxXCkc3MBIIO1oIafoKW60bwWXXq-mb_oESkLV9LDqh_bfPFsZSPe8io4BgFsDXlL5T-PB4NOG38KjpSrZO4pXzxLDXi5c_FFNGLHCbG1KkkB55GCHF4oTBzg1xi7oYgjFY46NbcnbNQaZK2kypqgSrpbpjJeaIF0_EK3wWs4Ix0rlzQR3Q
    hc_vault: []
    age:
        - recipient: age12nc5tc37e70nxpjn7rulvn650l6wztftq75audd4nftpue4jp3uqdac6el
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOXovRnl5YUlqZ1pOOTZT
            MzE4dm5naHRaSzVKUEpUejNQMzhuT3pPbVZJCnhVYkhaM3hDdS9RU0VQTU9MMW54
            N05pdVdqYmZHaTdmRkZySkFBbnQ2aVkKLS0tIFk5eVNzN0tXTW1EWXN4Ynl2eUJT
            YWxUQzVaREFDQktQY09mbWVLRE1LNjAK2N1lXkb+1tS+jiM2fQ8XDxiOhyRfmRnz
            LEIqh4sIRcFDb3W7FOT43u5xbsLnLPaGw6PSsAgUVHk7JpKx/Oah7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-01T22:28:23Z"
    mac: ENC[AES256_GCM,data:c1zGd/AEazVQ24C3a6rFR24skCuaZjI/eUtX7kR7HCfOKs24egGK73lKwb9YXVJ2qUOtypkygM7URfwewV6I0Fk2t5s9YIAhaBGND3WeilulwNAgX1tcBUWyCF+EfrF2lbBO+dmo92uFrfTLoeBjCvdCZbehj4uoyNAlkjkYQew=,iv:Cu1tuUiSARvmVrlDObuyatSEE0Uw3jCUQrqEV81UdWU=,tag:tcYTRKaPsJuWePxRRLWvgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
