---
apiVersion: v1
kind: Namespace
metadata:
  name: contour
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: contour
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: contour
spec:
  interval: 30m
  chart:
    spec:
      chart: contour
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: contour
      interval: 12h
  values:
    installCRDs: true