resources:
  - namespace.yaml
  - helm-release.yaml

configMapGenerator:
  - name: cert-manager-values
    namespace: flux-system
    files:
      - values.yaml=cert-manager-0.12.5-values.yaml

configurations:
  - valuesfrom.yaml