resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml

configMapGenerator:
  - name: cert-manager-values
    namespace: flux-system
    files:
      - values.yaml=cert-manager-v1.13.1-values.yaml

configurations:
  - valuesfrom.yaml