apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../bases/podinfo
- ../bases/matterbridge

patches:
- path: podinfo-release.yaml

secretGenerator:
- name: matterbridge-config
  namespace: matterbridge
  files:
  - matterbridge.yaml=matterbridge-config.yaml
