apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: "6.6.1"
  values:
    replicaCount: 2
    serviceMonitor:
      enabled: false
      interval: 15s
      additionalLabels: {}

    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 64Mi
    hpa:
      enabled: true
      maxReplicas: 5
      requests: 100
    ui:
      color: "#34577c"
      message: "Greetings"
      logo: https://raw.githubusercontent.com/PowerShell/PowerShell/master/assets/Square150x150Logo-Preview.png