apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
#  - ingress.yaml
  - httproute.yaml
  - hpa.yaml