apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: podinfo
spec:
  hostnames:
  - poshcode.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: cilium
    name: gateway
    sectionName: https-poshcode
  rules:
  - backendRefs:
    - name: podinfo
      port: 9898
    matches:
    - path:
        type: PathPrefix
        value: /

