apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: cillium
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    service.beta.kubernetes.io/azure-dns-label-name: poshcode
spec:
  gatewayClassName: cilium
  listeners:
  - name: http-1
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchExpressions:
            - key: poshcode.com/http-allowed
              operator: "true"
  - name: https-1
    allowedRoutes:
      namespaces:
        from: All
    protocol: HTTPS
    port: 443
    hostname: poshcode.com
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: poshcode-tls