apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      version: "1.17.x"
  values:
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true

    extraArgs:
    - --enable-gateway-api
