apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  targetNamespace: monitoring
  chart:
    spec:
      version: "61.3.x"
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-values