apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager
  - ../base/dex
  - ../base/monitoring
  - ../base/networking
patches:
  - path: cert-manager-release.yaml
    target:
      kind: HelmRelease
      name: cert-manager
  - path: dex-release.yaml
    target:
      kind: HelmRelease
      name: dex
  - path: dex-route.yaml
    target:
      kind: HTTPRoute
      name: dex
  - path: networking-gateway.yaml
    target:
      kind: Gateway

