apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../bases/cert-manager
  - ../bases/dex
  - ../bases/monitoring
  - ../bases/networking
patches:
  - path: cert-manager-release.yaml
    target:
      kind: HelmRelease
      name: cert-manager
  - path: dex-release.yaml
    target:
      kind: HelmRelease
      name: dex
  - path: networking-gateway.yaml
    target:
      kind: Gateway

