apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack-secret.yaml
  - ../bases/cert-manager
  - ../bases/dex
  - ../bases/kube-prometheus-stack
  - ../bases/networking
  - ../bases/loki-stack
patches:
  - path: cert-manager-release.yaml
    target:
      kind: HelmRelease
      name: cert-manager
  - path: dex-release.yaml
    target:
      kind: HelmRelease
      name: dex
  - path: kube-prometheus-release.yaml
    target:
      kind: HelmRelease
      name: kube-prometheus-stack
  - path: loki-stack-release.yaml
    target:
      kind: HelmRelease
      name: loki-stack
  - path: networking-gateway.yaml
    target:
      kind: Gateway

configMapGenerator:
  - name: prometheus-values
    namespace: flux-system
    files:
      - values.yaml=kube-prometheus-values.yaml

configurations:
  - valuesfrom.yaml