apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
spec:
  targetNamespace: monitoring
  chart:
    spec:
      version: "2.x"
  values:
    promtail:
      enabled: true
    loki:
      enabled: true
      isDefault: false
      serviceMonitor:
        enabled: true
        additionalLabels:
          app.kubernetes.io/part-of: kube-prometheus-stack
      config:
        chunk_store_config:
          max_look_back_period: 0s
        table_manager:
          retention_deletes_enabled: true
          retention_period: 12h