apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  releaseName: dex
  targetNamespace: dex
  chart:
    spec:
      chart: dex
      version: "0.15.3"
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 5
  rollback:
    timeout: 5m
  valuesFrom:
  - kind: ConfigMap
    name: dex-values
