apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  # Workload Identity (note: you must copy the client id from the output of your deployment)
  - patch: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: controller
        annotations:
          azure.workload.identity/client-id: 429675bd-e5c8-41fe-9ac7-1055f14261e6
          azure.workload.identity/tenant-id: b3714c3f-ecbc-453f-8ae4-ddeeb141a966
    target:
      kind: ServiceAccount
      name: "(source-controller|helm-controller|image-reflector-controller|kustomize-controller)"
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: controller
        labels:
          azure.workload.identity/use: "true"
      spec:
        template:
          metadata:
            labels:
              azure.workload.identity/use: "true"
    target:
      kind: Deployment
      name: "(source-controller|helm-controller|image-reflector-controller|kustomize-controller)"
  # SOPS Configuration
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: controller
      spec:
        containers:
        - name: manager
          env:
          - name: AZURE_AUTH_METHOD
            value: msi
    target:
      kind: Deployment
      name: "(kustomize-controller)"
  # Enable OOM watch feature
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --feature-gates=OOMWatch=true
      # Threshold at which to trigger a graceful shutdown (optional, default 95%)
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --oom-watch-memory-threshold=95
      # Interval at which to check memory usage (optional, default 500ms)
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --oom-watch-interval=500ms
    target:
      kind: Deployment
      name: helm-controller