apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- bootstrap.yaml

patches:
# Workload Identity. You must set the client-id and tenant-id
- target:
    kind: ServiceAccount
    name: "(helm-controller image-reflector-controller kustomize-controller source-controller -join '|')"
  patch: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: controller
      annotations:
        azure.workload.identity/client-id: 4473bf75-dced-48aa-85bf-db4a18edc16e
        azure.workload.identity/tenant-id: b3714c3f-ecbc-453f-8ae4-ddeeb141a966
- target:
    kind: Deployment
    name: "(helm-controller image-reflector-controller kustomize-controller source-controller -join '|')"
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: controller
      labels:
        azure.workload.identity/use: "true"
    spec:
      template:
        metadata:
          labels:
            azure.workload.identity/use: "true"

# Enable Helm OOM watch feature
- target:
    kind: Deployment
    name: helm-controller
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --feature-gates=OOMWatch=true
    # Threshold at which to trigger a graceful shutdown (optional, default 95%)
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --oom-watch-memory-threshold=95
    # Interval at which to check memory usage (optional, default 500ms)
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --oom-watch-interval=500ms

# Azure Authentication Method for SOPS
- target:
    kind: Deployment
    name: "(kustomize-controller)"
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: controller
    spec:
      containers:
      - name: manager
        env:
        - name: AZURE_AUTH_METHOD
          value: msi
