apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-telemetry-demo
spec:
  interval: 4h
  timeout: 7m
  releaseName: open-telemetry-demo
  targetNamespace: open-telemetry
  chart:
    spec:
      chart: opentelemetry-demo
      version: "0.36.1" # This chart does not support upgrade
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
      interval: 12h
  install:
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 3
      strategy: uninstall # if the ugprade fails, start over with a fresh install
      remediateLastFailure: true

  valuesFrom:
  - kind: ConfigMap
    name: open-telemetry-demo-values
