apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  releaseName: cert-manager
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: "0.12.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
  rollback:
    timeout: 5m
  valuesFrom:
  - kind: ConfigMap
    name: cert-manager-values