apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: monitoring
  name: kube-prometheus-stack-grafana
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: networking
    name: damascus
    sectionName: https-grafana
  rules:
  - backendRefs:
    - name: kube-prometheus-stack-grafana
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: monitoring
  name: kube-prometheus-stack-prometheus-prometheus-poshcode-com
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: networking
    name: damascus
    sectionName: https-prometheus
  rules:
  - backendRefs:
    - name: kube-prometheus-stack-prometheus
      port: 8081 # OAuth proxy to 9090
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: monitoring
  name: kube-prometheus-stack-alertmanager-alerts-poshcode-com
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: networking
    name: damascus
    sectionName: https-alerts
  rules:
  - backendRefs:
    - name: kube-prometheus-stack-alertmanager
      port: 8083 # OAuth proxy to 9093
    matches:
    - path:
        type: PathPrefix
        value: /
