apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - namespace.yaml
- middleware.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
- secret-dex.yaml # this one worked: secret-azuread.yaml

#
# Configs
#
configMapGenerator:
- name: configs
  namespace: traefik
  files:
    - rules.ini
