apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
spec:
  minReadySeconds: 3
  replicas: 1
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: traefik-forward-auth
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: traefik-forward-auth
        image: ghcr.io/jordemort/traefik-forward-auth:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 4181
          protocol: TCP
        env:
        - name: DOMAIN
          value: "poshcode.com"
        - name: COOKIE_DOMAIN
          value: "poshcode.com"
        - name: AUTH_HOST
          value: "auth.poshcode.com"
        - name: LOG_LEVEL
          value: "trace"
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: azuread
              key: random_secret
        - name: DEFAULT_PROVIDER
          value: "oidc"
        - name: PROVIDERS_OIDC_ISSUER_URL
          valueFrom:
            secretKeyRef:
              name: azuread
              key: endpoint
        - name: PROVIDERS_OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azuread
              key: client_id
        - name: PROVIDERS_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azuread
              key: client_secret
        # - name: CONFIG
        #   value: "/config"
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
      #   volumeMounts:
      #   - name: configs
      #     mountPath: /config
      #     subPath: traefik-forward-auth.ini
      # volumes:
      # - name: configs
      #   configMap:
      #     name: configs

