apiVersion: v1
kind: Secret
metadata:
    name: azuread
type: Opaque
data:
    client_id: ENC[AES256_GCM,data:scWj70FpiofuLcu7zA6AjE02dzumK4+R7nUQNqjngBa8qdjJu+a0f7IoCsYJOU31,iv:Y4Zd373hISTEyH5SMYb2S1VLEYdGaarxqIPuLw8N8EQ=,tag:z65InDZOylhobYCeka9IQw==,type:str]
    client_secret: ENC[AES256_GCM,data:PAhkjdX/DSVptUvKi7N6eWLytdIs6K5e17269MfIhsG1Gx2CtJJvhZ4pm4cyH0ztFNAeH6dp3rA=,iv:mzg5bhvW/pZR/hWWDpwP++bTh6qJRrgA5dBQRdlpcP0=,tag:uJf2bYbbnIOg8Y1Od5pMDA==,type:str]
    endpoint: ENC[AES256_GCM,data:sUTE5nL2L5S/pee2Dd39uFsfPjJJQmgQK9W/R9QBLxfPoSn5WxxmjwzpJTNOLaEJtG/TFHXPoOiEjHuCtx4dsbCDFpEEvwBkpB/J,iv:xQ+pioYs8DItcEJ/MTyTd3thzhG33AyFixpSy4gWgdo=,tag:rmOs2IAJ6impKs+Kmy+qsA==,type:str]
    random_secret: ENC[AES256_GCM,data:HS1hkpeqZh9zM/KoDGF+F1AVD9MlgnrMYJPDP3eUiR47UGVGknoVz09vwPAazByi,iv:48/LAch0madXlvbuFbjl3ysmDXHGIEZTmZ9WmqGkYSo=,tag:NeCsxYp6cpmmuRwVJ4IXKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://kv-joel.vault.azure.net
          name: sops-key
          version: 5ef3f03a360140bbb419a997adb4ea3d
          created_at: "2023-10-04T04:16:12Z"
          enc: QURjp6VteplTn7AF7sr4SCX8bW2PAThSl80YXsmVzEehqPsH2hfBtOkmIYx0AZJuhFqy4IWjbZb00LOF3_vKMuy9kmlgwMU_JrUKcGQv21Wcy1vZF7GYhOGDEv1zpJMuiqote2BaV2H-jAJ2NRQHWmbxTf1BBHhXtOTyZ7CgytPninuQgaGzsZuMTexC8Sz4-s1mGkPyeg0x8hy246q1VJkH_fxzSpmV6XqtwltApIbdsb6VdDk4Xk4TfRqfnF7yLfT9MwlAnZ8-utV3kZDqq9JYUJV7hihhjQTrei_XEeOM4BNam7LrSVX9XJdz8TIyyTsC_0i93d_G3_kraUsAPYux1Qlj8BydJzphqXFDF5vJm2oem5EzQSydDwDPYxLm5YOXBDuUS2llYNZ9a3BDr1Dw9JFqZtPc5I2OSt4o_-SVxYEfVHx4Dy-XFxDbzf1Q9Smwc1k6cIRfhYVFxYsZeN6P41XgbxC4RH6P4iABZ2zE2M6QTbmLJOCMd4edIUXfjUOCnk7hUdvDGOMP7IrTkeSJ3BqnAPP-AC4NB01oZjLWMqw1NlXZt7nmCU40VM57vTGeoiFl5McvtpWE-SUBunTcuGQET-VC2krq9I2Y9nNBBo1gdBUTT6914lGkKJmq25xqM1cRBM_Ux_uKCioyGiioykyn8cmDKjtsbg_cKIo
        - vault_url: https://kv-poshcode.vault.azure.net
          name: sops-key
          version: f49a0e054ffe451a85df33e5cdf7946a
          created_at: "2023-10-04T04:16:12Z"
          enc: KzqUBo5sPdKHOUAQIJQBvI_77Mf87ZC2z2lLO5159-vce3dkgqYGgHbSZXN2b-vW2ar4RQnhrsCyXVf6mgacgztVlhA_DfctTg_9_CN5XbdOiwax66CVckI3eMHyv4PbWz6odR91xRHlSRr78JEhFtle9EKWbtCw3YHmu2s18tY9jiAvXP2HvtZhGdQL6y-uuiyDDsQmIO8ACu6ByJirHp3PO-3jWJOB9bfqPYCFq700s8LVHhTwhb8aKR0jfrOY0R0Wedz2zDYvbHYSD9TRMVdv94XycliIJfivFVkkxjj-euCdyV8Kp3ASqjqBYKllxYzpNXupd9YkmLL8CADvBQ
    hc_vault: []
    age:
        - recipient: age12nc5tc37e70nxpjn7rulvn650l6wztftq75audd4nftpue4jp3uqdac6el
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdlJ5Qi8wMjBCRnVwZy9V
            cWZRQ0F3YmhPbENwSG5CbFZpTlc3Qi9CeUhVCmZQMmdrZnRseTYrQWJUVy9jaVJP
            Rkl3S3NSL3lnaExVdHcyNFA5RUZ5TFkKLS0tIGlwQXAwZGR2enBQNzZvV24wU3JC
            TG9oTnRPVGpjdUxhZnlzTTNNcDVxN0UKjfnXjekuBtcyIROezKKRtJ7MaSg3W4g2
            ETGiwR7mS4oRXX/SjD7tiH1AjzHDkVKRLLbsNPPiFjnpgjLBXb01KQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-04T04:16:15Z"
    mac: ENC[AES256_GCM,data:e0XqsKXHHea/+B6Xdwa7aJomMbEAX7d0MmZUIa/0cZYYiJG+UuXpgkybTEW5BZTp73F+QuPvAHZxbUdRnqDrbxdJ5Jx+PWfVYvexyTpPnYT/IQC63h74LTopda2xRm00tuzSMLr7xmM5rsD6Y3C8SQeUgSN4Nec/CNtCmC7ptfE=,iv:1WUyK5AT891oRVUdnXST8DxZGbszIpKrXzz+m7Kp5FQ=,tag:kdXUdVAhlJ4eBFApzJWnwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
