apiVersion: v1
kind: Secret
metadata:
    name: azuread
    namespace: auth
type: Opaque
data:
    client_id: ENC[AES256_GCM,data:AkocYDEEXJv2z4LFqxrsRadQ2PvjRmPsDfM6rRvT891ApSIoAd0DAj1z1bgitoTU,iv:zQseg0PFoQ+r6Rk6OpeJAlM1w04Gb0cfOf+SdzWg/eA=,tag:xouufPIaN8CbQ8vPQWkDGw==,type:str]
    client_secret: ENC[AES256_GCM,data:PL7l0+S3sZyP5jHOg3xMVugUcJe3WC8nNojDgpnlWecpdn0C6TylpGUZ2hKiOqwyf8YTiA/IcVk=,iv:lTZYMRihSfEFB+w3WRX9vwClbm49Omsn0nOiU8I2BsE=,tag:YvKbrh4hSm9AatR0pS6Nxw==,type:str]
    endpoint: ENC[AES256_GCM,data:7okTiH/srr4AjoKp0QUMA3iTsvX354W3Pk34GyFVVxphUlb2fvROpeITBc0BOACfLIIZ4W+IKEms6Tlg5HF9IqPss31OJgY9ZPP4c0NyUiRUuel41rcnFu8pg/bKWqa4DQqfWg==,iv:tDvpk5wvwhfDREU0tgUMw5+VG+Ylq4HKoTNIBp7kSMw=,tag:dxTmFf4uU2ETrPmMwFJ6Xg==,type:str]
    random_secret: ENC[AES256_GCM,data:pRH6o9NU7HaXn7FAu9+7DHh69SehxYNNXPfsjkBmCbc+eN+NadFXuC9thcsObe+7,iv:MxUfJHNdCbrrRy+xSbL4UVK0S1QVVf8o3XJfUFyutdk=,tag:em0J6WaOTIZ8x4c181SF4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://kv-joel.vault.azure.net
          name: sops-key
          version: 5ef3f03a360140bbb419a997adb4ea3d
          created_at: "2023-10-07T21:49:43Z"
          enc: c27ewIBNd7I3oTqbWCW2O5YBhqyAh1mD33kuvzcBM-pZ9UI4wuP_N1oBrP9yWnTVPivG9gh-1Fa9SQLFVzp_CSaFMcm4PXqLd7XuSpXQTVm1sMPfUT-q3t_vMkCQqoKyCtfJYNqHIVcCaROzZGO7B1qFM7knSijNoAoxyhCW6gCFZuanGx_sbPF8uVxaKU8dVPrMoxyOkMo1PhfV-X65faBV4T_8fKlb4MLVStsRVDlQRuQf-IKpX1r8U66HkPWdcr3jlShTqDxEE_Ezn8l9WICnhc7y5Oug-YV8YRdKdX2tNtZA25S9o-GVQffM8MnXqxVu8P2sFoagb3LknbxYqFxo8MMNRdCr0NCcS8P3JzvX9RVrlWIjYJfWr8oTnAp3Utjj3qasxbCcsbRYVgPtATK_9OKJhiLwhqFeLlfYzGor__pXqM0ED1cNhazQWtRqb-39D8_bi5GqxTZ_3AyjoEd3au_efGa-5nVgN-7rLNYCxMt7RAkv6Q4fN8l3-jKgtYHDKr252O6y_npCAimG-wsP3ypwXJ9VTyRwpOrv1PSUp9QAltcVMGufDarz8ptA9eRIxQOLYr4lQalRk2HpthyJdnlcSGEi40K1lCARehqaWoQh_JoWYXlpYtbbkJLrowmUW9MUWBq3aBt-RseRrwVDKc1x0FC2AL5uRIOQA8M
        - vault_url: https://kv-poshcode.vault.azure.net
          name: sops-key
          version: f49a0e054ffe451a85df33e5cdf7946a
          created_at: "2023-10-07T21:49:43Z"
          enc: T2Hx51QjTjJDM6_sO1bzom7vlJwy26QyTWYB_McUpWJWEQhtobheVl8-zb-c3_J3wQbLLMfEjYLbS32AvLVFsDja8PWRcL8XufQS5ErGjaOUMlKqaGDsSZRM67HvzOh61vVjVCGPxGSItW8wBG86Qe9iisO7nHvgxwXUGxupXA626itJeqqUURzRPAblV_2EALuxg5Muv0XzzElt6GTS1LzAPI7tvbjZrKEC5S-5Hq1In2d0A_ETtjIV5vv8gZKZnQklC9bOCbhrxjKhNqgIW8Bmt9srjOIW7MagJWSMcrBdgyn1Tf1yiFLOWTAx7jIEtmzeJi8XMvEdO07Ys8kNOw
    hc_vault: []
    age:
        - recipient: age12nc5tc37e70nxpjn7rulvn650l6wztftq75audd4nftpue4jp3uqdac6el
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RmtQdGp4WDJQQms2Qitl
            ay9aL0xkSVJENko5Vm5wVzFrMVhKUnpvUUhjCkJJT3M5SHRYaEdWMTlMZHZvQkhW
            ekFuUXhaeWMvZE1Ud2N4K2p2U1h2SWMKLS0tIFBZaHJzTit5MjNiVXZFR0pUQzF1
            OStZc3ZTVFBvMGgzVHZ1ZlgvYWtiZnMKlgj3ZX7nvlMQsjNUWZBk7MAr6LDteRNG
            UA91nwo5LHyCUuUIEjzI1gvsQpcHMfZHuyPP+VL+ClGBy5nwj7qrNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-07T21:49:47Z"
    mac: ENC[AES256_GCM,data:N8c0my6sMrlO9cPimPnzQMJANirSTy0FZJQDAktA+F4/zXzTCnYbMAfGZ/lF2yEkpqK+qKEks3KFfgO/FWMi8FdJEO1kdtHtpEURUg/qibFPuYeU21inhu8uw/r7uN8CAiSbU1Oj+35tcsFoSPaINSgKWdlhTd+Upt9Vt/osnso=,iv:4jda59POmcRfTWucbfHYzRutfA96ymCYxK+Elv/4fAU=,tag:GHaTo7lUPaUCBQ9IZ6FN3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
